name: foodly
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  modal_progress_hud_nsn: ^0.2.1
  page_transition: "^2.0.9"
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^10.2.1
  introduction_screen: ^3.0.2
  smooth_page_indicator: ^1.0.0+2
  expandable: ^5.0.1
  provider: ^6.0.4
  geolocator: ^9.0.2
  loading_indicator: ^3.1.0
  http: ^0.13.5
  firebase: ^9.0.3
  firebase_core: ^2.0.0
  form_field_validator: ^1.1.0
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/search_images/
    - assets/search_results/
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logobgremoved.png